export { default as GrayLogo }  from './Logo/gray'
export { default as PinkLogo }  from './Logo/pink'
export { default as Switch }  from './Switch/index'
export { default as Github }  from './Github/index'
export { default as DarkGithub }  from './Github/dark'
export { default as Linkedln }  from './Linkedln/index'